gripper_teleoperation:
  joystick:
    open_button: 
      type: int
      default_value: 0
      description: "Button to open the gripper for binary control"
    close_button: 
      type: int
      default_value: 1
      description: "Button to close the gripper for binary control"
    toggle_button:
      type: int
      default_value: -1
      description: "Button to toggle the gripper state for binary control (-1 for no toggle button)"
    gripper_axis:
      type: int
      default_value: 2
      description: "Axis to control the gripper position for continuous control"

  max_position:
    type: double
    default_value: 0.01
    description: "Maximum position for the gripper in meters"

  publishing_rate:
    type: int
    default_value: 100
    description: "Publishing rate for the gripper state topic in Hz (set to 0 to disable publishing)"
    