gripper_teleoperation:
  joystick:
    topic: 
      type: string
      default_value: "/joy"
      description: "Topic for joystick input"
    open_button: 
      type: int
      default_value: 0
      description: "Button to open the gripper for binary control"
    close_button: 
      type: int
      default_value: 1
      description: "Button to close the gripper for binary control"
    toggle_button:
      type: int
      default_value: -1
      description: "Button to toggle the gripper state for binary control (-1 for no toggle button)"
    gripper_axis:
      type: int
      default_value: 2
      description: "Axis to control the gripper position for continuous control"

  command_topic:
    type: string
    default_value: "/gripper_command"
    description: "Topic name for publishing the gripper action command"

  max_position:
    type: double
    default_value: 0.01
    description: "Maximum position for the gripper in meters"

  state_topic:
    type: string
    default_value: "/gripper_state"
    description: "Optional topic name for publishing the current controller gripper state as a normalized value between 0.0 and 1.0"

  publishing_rate:
    type: int
    default_value: 100
    description: "Publishing rate for the gripper state topic in Hz (set to 0 to disable publishing)"
    