pose_teleoperation:
  virtual_world_frame_id:
    type: string
    default_value: "virtual_world"
    description: "Frame ID for the virtual world (reference frame for the 3D tracking controller)"
  controller_frame_id:
    type: string
    default_value: ""
    description: "Frame ID for the joystick controller (used for input filtering)"
  base_frame_id:
    type: string
    default_value: "base_link"
    description: "Frame ID for the robot arm base"
  end_effector_frame_id:
    type: string
    default_value: "gripper_link"
    description: "Frame ID for the robot arm end effector"

  joystick:
    calibrate_button:
      type: int
      default_value: 7
      description: "Button to calibrate the frame"
    teleoperate_button:
      type: int
      default_value: 2
      description: "Button to start/stop teleoperation (while being pressed)"
    home_button:
      type: int
      default_value: 3
      description: "Button to home the end effector"

  frame_transform:
    type: double_array
    default_value: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    description: "Transform between the robot base and the controller frame to calibrate the world frame ([x, y, z, roll, pitch, yaw] in meters and radians)"

  filter:
    error:
      x: 
        type: double
        default_value: 0.2
        description: "Ignore all inputs which deviate by a given distance in the x axis from the previous command."
      y: 
        type: double
        default_value: 0.2
        description: "Ignore all inputs which deviate by a given distance in the x axis from the previous command."
      z: 
        type: double
        default_value: 0.2
        description: "Ignore all inputs which deviate by a given distance in the x axis from the previous command."
    smoothing_factor:
      type: double
      description: "Smoothing factor between 1.0 (no smoothing) and 0.1 (high smooting, with latency)"
      default_value: 0.9
      validation:
        bounds<>: [0.01, 1.0]

  home:
    joint_controller_name:
      type: string
      default_value: "joint_trajectory_controller"
      description: "Name of the joint controller to use for homing"
    joint_names:
      type: string_array
      default_value: []
      description: "Names of the joints to home"
    joint_positions:
      type: double_array
      default_value: []
      description: "Positions of the joints to home"

  cartesian_controller_name:
    type: string
    default_value: "cartesian_motion_controller"
    description: "Name of the Cartesian controller to use for teleoperation"